"""Distance correlation powered by Mojo."""

from ._dcor import (
    CompileMode,
    DistanceCovarianceMethod,
    EstimationStatistic,
    Stats,
    distance_correlation,
    distance_correlation_af_inv,
    distance_correlation_af_inv_sqr,
    distance_correlation_sqr,
    distance_covariance,
    distance_covariance_sqr,
    distance_stats,
    distance_stats_sqr,
    double_centered,
    mean_product,
    partial_distance_correlation,
    partial_distance_covariance,
    u_centered,
    u_complementary_projection,
    u_distance_correlation_sqr,
    u_distance_covariance_sqr,
    u_distance_stats_sqr,
    u_product,
    u_projection,
)

__version__ = "0.1.0"

__all__ = [
    "CompileMode",
    "DistanceCovarianceMethod",
    "EstimationStatistic",
    "Stats",
    "distance_correlation",
    "distance_correlation_af_inv",
    "distance_correlation_af_inv_sqr",
    "distance_correlation_sqr",
    "distance_covariance",
    "distance_covariance_sqr",
    "distance_stats",
    "distance_stats_sqr",
    "double_centered",
    "mean_product",
    "partial_distance_correlation",
    "partial_distance_covariance",
    "u_centered",
    "u_complementary_projection",
    "u_distance_correlation_sqr",
    "u_distance_covariance_sqr",
    "u_distance_stats_sqr",
    "u_product",
    "u_projection",
]
